version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: directus
            MYSQL_DATABASE: directus
            MYSQL_USER: directus
            MYSQL_PASSWORD: directus

    directus:
        depends_on:
            - db
        build:
            context: ./
        ports:
            - "8080:8080"
        restart: always

volumes:
    db_data: {}